-- 테이블 생성

DROP TABLE BIGDATA_MEMBER;

CREATE TABLE BIGDATA_MEMBER(
    ID VARCHAR(50) PRIMARY KEY,
    PW VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL, 
    AGE NUMBER NOT NULL,
    POINT NUMBER DEFAULT 0
);